### ISSUE TITLE
Help!!! Cannot read region files with negative coordinate (like r.-2.-1.mca)

### ISSUE THREAD

**Issue by Himmelt** [thejonwithnoh/mca-js#1]
`nbt-js` seems to have some bugs.
source code:

```
var fs   = require('fs');
var mca  = require('mca-js');
var nbt  = require('nbt-js');

var file = fs.readFileSync('r.-1.-1.mca');
var data = mca.getData(file,0,0);
var tag  = nbt.read(data);
console.log(JSON.stringify(tag.payload));
```

error code:

```
C:\Users\Himmelt\Desktop\nbtjs\node_modules\nbt-js\nbt-js.js:66
                                var word = this.buffer['read' + type.format](this.offset);
                                                      ^

TypeError: Cannot read property 'readInt8' of undefined
    at nbt.Reader.(anonymous function) [as byte] (C:\Users\Himmelt\Desktop\nbtjs\node_modules\nbt-js\nbt-js.js:66:27)
    at read (C:\Users\Himmelt\Desktop\nbtjs\node_modules\nbt-js\nbt-js.js:48:30)
    at Object.nbt.read (C:\Users\Himmelt\Desktop\nbtjs\node_modules\nbt-js\nbt-js.js:110:2)
    at Object.<anonymous> (C:\Users\Himmelt\Desktop\nbtjs\main.js:7:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
```

Help!! T_T 

```
os: win10 x64
mc: 1.7.10 & 1.7.10-forge
```

**Comment by thejonwithnoh** [comment]
I'm having trouble recreating the issue.  Are you sure that chunk 0, 0 is defined in your r.-1.-1.mca file?  I'm assuming if you were to add `console.log(data);` right after `var data = mca.getData(file,0,0);` that it would print `undefined`?  This is the current behavior when attempting to get data from a chunk that hasn't generated in the region file yet.  Let me know if this helps!

**Comment by Himmelt** [comment]
Oh! The chunck was really not generated. It's my negligence. Thx ^_^
I'm not good at coding, can this model write chunck data back to the region file ?

**Comment by thejonwithnoh** [comment]
No problem, it's an easy enough mistake to make.  As for writing data, the current version does not support it, but it's currently in the works!  Some other projects have taken my attentions recently, but I do hope to have a version of mca-js and nbt-js with write capabilities soon.
